### ISSUE TITLE
마켓 업로드를 프로젝트 설정

### ISSUE THREAD

**Issue by goodmorningcody** [AnAppPerTwoWeeks/bookmark-app#33]
- 아이콘 준비 및 적용
 - 스크린샷 준비
 - 스플래쉬 이미지 준비 및 적용
 - 애플 개발자 계정 준비

**Comment by mainendp** [comment]
스플래쉬 이미지, 아이콘 적용, 스크린샷 준비했습니다.
커밋해서 푸쉬만 하고 풀리퀘는 애플 개발자 계정 준비까지 되면 할게요.

<img width="93" alt="App_icon" src="https://user-images.githubusercontent.com/60657105/75096178-5f696780-55e0-11ea-8843-fbb9c6cf8cb2.png">
<img width="1309" alt="스크린샷 2020-02-23 오전 2 08 11" src="https://user-images.githubusercontent.com/60657105/75096279-82484b80-55e1-11ea-9429-4aea00e94b41.png">

**Comment by mainendp** [comment]
애플 개발자 계정도 준비 되었습니다.
